
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>База данных</title>
    <style>
        .btn {
            display: inline-block;
            background: #8C959D;
            color: #fff;
            margin-bottom: 5px;
            padding: 1rem 1.5rem;
            text-decoration: none;
            border-radius: 3px;
        }
    </style>
</head>
<body>

<div id="idDivTarget">


</div>



<script type="text/javascript">
    $(document).ready(function (){
        $.ajax({
            type: 'POST',
            url: '/db/Connect',
            data: {action:'showTable'},
            success:function (output) {
                $('#idDivTarget').text(output);
            },
            error:function () {
                $('#idDivTarget').text('404');
            }
        });
    });





</script>



<br>
<a href="dbCreate/dbCreate" class="btn">Создать новую таблицу</a>

</body>
</html>
<br>









