


<?php foreach ($this->getChildren() as $child): ?>
    <?php $child->toHtml() ?>
<?php endforeach ?>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Начало</title>
    <style>
        .btn {
            display: inline-block;
            background: #8C959D;
            color: #fff;
            margin-bottom: 5px;
            padding: 1rem 1.5rem;
            text-decoration: none;
            border-radius: 3px;
        }
    </style>
</head>
<body>
<a href="table/table" class="btn"> Поле </a> <br>
<a href="db/db" class="btn">База данных</a>

</body>
</html>
<br>

