


<?php foreach ($this->getChildren() as $child): ?>
    <?php $child->toHtml() ?>
<?php endforeach ?>


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Кнопка</title>
    <style>
        .btn {
            display: inline-block;
            background: #8C959D;
            color: #fff;
            padding: 1rem 1.5rem;
            text-decoration: none;
            border-radius: 3px;
        }
    </style>
</head>
<body>
<a href="table/table" class="btn">Начало </a>
</body>
</html>
<br>

