<?php
namespace App\View;





?>


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!--    <link rel="stylesheet" type="text/css" href="/css/style.css" />-->
    <title>Поле битвы</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css" />
</head>


<form>
    <body>
        <br>
            <h1>Добро пожаловать!</h1>
        <br>
            <h1>Карты первого игрока</h1>
        <br>

    </body>
</form>
