<?php
foreach ($this->getChildren() as $child):
    $child->toHtml();
endforeach;

if(!empty($_POST)){

}else{
    // echo json_encode(['success' => 0]);
}


?>
<head>
<script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous">
</script>
<style>
    dd{
        display: inline;
    }
    .normal{
        display: block;
    }

</style>

</head>
<form method="post" action="middle.phtml">

    <dl>
        <dt> Первый игрок</dt>
            <?php for($i=0; $i<7; $i++): ?>
                <dd><input type="submit" id="idF<?php $i ?>" class="ferDeck" value="<?php $this->getCardFromDeck($i) ?>" onclick="return false">  </dd>
            <?php endfor?>

    </dl>
<!--    $('#ferDeck')-->

<dl>
    <dt> Силы первого игрока</dt>
        <dd>
            <dt>
                <dd class="normal"> <output name="fp1"> </output> </dd>
                <dd class="normal"> <output name="fp2"> </output> </dd>
                <dd class="normal"> <output name="fp3"> </output> </dd>
            </dt>
        </dd>
        <dd></dd>
        <dd></dd>
        <dd></dd>
        <dd></dd>
        <dd></dd>
        <dd></dd>
    <dt> Поле битвы </dt>
        <?php for($i=0;$i<8;$i++): ?>
            <dd><input type="submit" id="idB<?php $i?>" value="<?php $this->getNumberBattlefild($i) ?>" onclick="return false"> </dd>
        <?php endfor?>


    <dt> Силы второго игрока</dt>
        <dd>
            <dt>
                <dd class="normal"> <output name="sp1"> </output> </dd>
                <dd class="normal"> <output name="sp2"> </output> </dd>
                <dd class="normal"> <output name="sp3"> </output> </dd>
            </dt>
        </dd>
    <dd></dd>
    <dd></dd>
    <dd></dd>
    <dd></dd>
    <dd></dd>
    <dd></dd>

    <dt> Второй игрок</dt>
        <?php for($i=0;$i<7;$i++): ?>
            <dd><input type="submit" id="idS<?php $i?>" value="<?php $this->getCardFromSecDeck($i)?>" onclick="return false"> </dd>
        <?php endfor?>



</dl>




</form>

